function [screenIndex] = FirstCannonSlide(screenIndex, taskParam, cannon)

    WaitSecs(0.1);
    if isequal(taskParam.gParam.taskType, 'dresden')
        if isequal(whichPractice, 'mainPractice')...
                || isequal(whichPractice, 'followCannonPractice')
            if isequal(subject.group, '1')
                txt=['Eine Kanone zielt auf eine Stelle des '...
                    'Kreises. Deine Aufgabe ist es, die '...
                    'Kanonenkugel mit einem Schild abzuwehren. '...
                    'Mit dem orangenen Punkt kannst du angeben, '...
                    'wo du dein Schild platzieren möchtest, '...
                    'um die Kanonenkugel abzuwehren.\nDu kannst '...
                    'den Punkt mit den grünen und blauen '...
                    'Tasten steuern. Grün kannst du für schnelle '...
                    'Bewegungen und blau für langsame Bewegungen '...
                    'benutzen.'];
            else
                txt=['Eine Kanone zielt auf eine Stelle des '...
                    'Kreises. Ihre Aufgabe ist es, die Kanonenkugel '...
                    'mit einem Schild abzuwehren. Mit dem orangenen '...
                    'Punkt können Sie angeben, wo Sie Ihr Schild '...
                    'platzieren möchten, um die Kanonenkugel '...
                    'abzuwehren.\nSie können den Punkt mit den '...
                    'grünen und blauen Tasten steuern. '...
                    'Grün können Sie für schnelle Bewegungen und '...
                    'blau für langsame Bewegungen benutzen.'];

            end
        else
            if isequal(subject.group, '1')
                txt=['Eine Kanone zielt auf eine Stelle des '...
                    'Kreises. Deine Aufgabe ist es, Kanonenkugeln '...
                    'mit einem Korb aufzusammeln. Mit dem orangenen '...
                    'Punkt kannst du angeben, '...
                    'wo du deinen Korb platzieren möchtest, um die '...
                    'Kanonenkugel aufzusammeln.\nDu kannst den '...
                    'Punkt mit den grünen und blauen Tasten '...
                    'steuern. Grün kannst du für schnelle '...
                    'Bewegungen und blau für langsame Bewegungen '...
                    'benutzen.'];
            else
                txt=['Eine Kanone zielt auf eine Stelle des '...
                    'Kreises. Ihre Aufgabe ist es, Kanonenkugeln '...
                    'mit einem Korb aufzusammeln. Mit dem orangenen '...
                    'Punkt können Sie angeben, '...
                    'wo Sie Ihren Korb platzieren möchten, um die '...
                    'Kanonenkugeln aufzusammeln.\nSie können den '...
                    'Punkt mit den grünen und blauen Tasten '...
                    'steuern. Grün können Sie für schnelle '...
                    'Bewegungen und blau für langsame Bewegungen '...
                    'benutzen.'];
            end
        end
    elseif isequal(taskParam.gParam.taskType, 'oddball')
        txt=['A cannon is aimed at the circle. Indicate where '...
            'you would like to place your shield to catch '...
            'cannonballs with the orange spot. '...
            'You can move the orange spot with the green and yellow '...
            'buttons. Green is for fast movements and yellow is '...
            'for slow movements.'];
    elseif isequal(taskParam.gParam.taskType, 'reversal') ||...
            isequal(taskParam.gParam.taskType, 'ARC')
        txt=['A cannon is aimed at the circle. Indicate where '...
            'you would like to place your shield to catch '...
            'cannonballs with the orange spot. '...
            'You can move the orange spot using the mouse.'];
    elseif isequal(taskParam.gParam.taskType, 'chinese')
        txt=['Du bist die Weltraumpolizei und beschützt deinen Planeten.\n'...
            'Ein fremdes Raumschiff zielt mit seiner '...
            'Kanone auf eine Stelle deines Planeten und feuert '...
            'Kanonenkugeln. Deine Aufgabe ist es, die Kanonenkugel mit einem '...
            'Schild abzuwehren. Mit dem orangenen Punkt kannst du '...
            'angeben, wo du dein Schild platzieren möchtest, '...
            'um die Kanonenkugel abzuwehren. Du kannst den Punkt mit '...
            'der Maus bewegen. Das kannst du jetzt ausprobieren.'];
    end

    if isequal(taskParam.gParam.computer, 'Dresden')
        Screen('TextSize', taskParam.gParam.window.onScreen, 19);
    else
        Screen('TextSize', taskParam.gParam.window.onScreen, 30);
    end
    distMean = 300;
    outcome = 300;
    taskParam.symbol = false;
    tickInstruction.savedTickmark = nan;
    tickInstruction.previousOutcome = nan;
    DrawFormattedText(taskParam.gParam.window.onScreen,...
        taskParam.strings.txtPressEnter,'center',...
        taskParam.gParam.screensize(4)*0.9);
    [taskParam, fw, Data, ~] = al_instrLoopTxt(taskParam,...
        txt, cannon, 'arrow', distMean, tickInstruction);
    if fw == 1
        screenIndex = screenIndex + 1;
    elseif bw == 1
        screenIndex = screenIndex - 1;
    end
    WaitSecs(0.1);
end