function MainJustInstructions(taskParam)
%MAINJUSTINSTRUCTIONS   This function runs the instructions for the change point condition
%
%   Input
%       taskParam: structure containing task parameters
%
%   Output
%       ~

screenIndex = 1;
while 1
    switch(screenIndex)
        
        case 1
            if isequal(taskParam.gParam.taskType, 'dresden') && (taskParam.subject.cBal == 4 || taskParam.subject.cBal == 6 || taskParam.subject.cBal == 5)
                txt = 'Kanonenkugeln Abwehren';
                screenIndex = YourTaskScreen(txt, taskParam.textures.shieldTxt, screenIndex);
            else
                screenIndex = screenIndex + 1;
            end
            
        case 2
            if isequal(taskParam.gParam.taskType, 'dresden') && (taskParam.subject.cBal == 4 || taskParam.subject.cBal == 6 || taskParam.subject.cBal == 5)
                
                header = 'Kanonenkugeln Abwehren';
                
                if isequal(taskParam.subject.group, '1')
                    
                    txt = ['In dieser Aufgabe ist das Ziel '...
                        'wieder möglichst viele Kanonenkugeln '...
                        'abzuwehren. Der Unterschied ist '...
                        'allerdings, dass du die Kanone '...
                        'diesmal nur noch selten sehen kannst.'];
                else
                    
                    txt = ['In dieser Aufgabe ist das Ziel '...
                        'wieder möglichst viele Kanonenkugeln '...
                        'abzuwehren. Der Unterschied ist '...
                        'allerdings, dass Sie die Kanone '...
                        'diesmal nur noch selten sehen können.'];
                end
                
                feedback = false;
                fw = al_bigScreen(taskParam, taskParam.strings.txtPressEnter, header, txt, feedback);
                if fw == 1
                    screenIndex = screenIndex + 1;
                    
                elseif bw == 1
                    screenIndex = screenIndex - 3;
                end
            else
                screenIndex = screenIndex + 1;
            end
            WaitSecs(0.1);
        case 3
            
            if isequal(taskParam.gParam.taskType, 'dresden')
                if taskParam.subject.cBal == 4 || taskParam.subject.cBal == 5 || taskParam.subject.cBal == 6
                    header = 'Erste Übung';
                else
                    header = 'Dritte Übung';
                end
            else
                header = 'Second Practice';
            end
            
            if isequal(taskParam.gParam.taskType, 'dresden')
                if isequal(taskParam.subject.group, '1')
                    
                    txt = ['Bis jetzt kanntest du das Ziel '...
                        'der Kanone und du konntest die meisten '...
                        'Kugeln abwehren. Im nächsten '...
                        'Übungsdurchgang wird die Kanone in den '...
                        'meisten Fällen nicht '...
                        'mehr sichtbar sein. Anstelle der '...
                        'Kanone siehst dann ein Kreuz. '...
                        'Außerdem siehst du wo die '...
                        'Kanonenkugeln landen.\n\n'...
                        'Um weiterhin viele Kanonenkugeln '...
                        'abzuwehren, musst du aufgrund '...
                        'der Landeposition einschätzen, auf '...
                        'welche Stelle die Kanone zielt und '...
                        'den orangenen Punkt auf diese Position '...
                        'steuern. Wenn du denkst, dass die '...
                        'Kanone auf eine neue Stelle zielt, '...
                        'solltest du auch den orangenen Punkt '...
                        'dorthin bewegen.\n\nWenn du die '...
                        'Kanone siehst, steuerst du dein Schild '...
                        'am besten genau auf das Ziel der Kanone.'];
                else
                    
                    txt = ['Bis jetzt kannten Sie das Ziel '...
                        'der Kanone und Sie konnten die meisten '...
                        'Kugeln abwehren. Im nächsten '...
                        'Übungsdurchgang wird die Kanone in den '...
                        'meisten Fällen nicht '...
                        'mehr sichtbar sein. Anstelle der '...
                        'Kanone sehen Sie dann ein Kreuz. '...
                        'Au?erdem sehen Sie wo die '...
                        'Kanonenkugeln landen.\n\n'...
                        'Um weiterhin viele Kanonenkugeln '...
                        'abzuwehren, müssen Sie aufgrund '...
                        'der Landeposition einschätzen, auf '...
                        'welche Stelle die Kanone zielt und '...
                        'den orangenen Punkt auf diese Position '...
                        'steuern. Wenn Sie denken, dass die '...
                        'Kanone auf eine neue Stelle zielt, '...
                        'sollten Sie auch den orangenen Punkt '...
                        'dorthin bewegen.\n\nWenn Sie die '...
                        'Kanone sehen, steuern Sie Ihr Schild '...
                        'am besten genau auf das Ziel der Kanone.'];
                end
                
            elseif isequal(taskParam.gParam.taskType, 'ARC')
                txt = ['In this block everything will exactly '...
                    'be the same except that you will only '...
                    'occasionally see the cannon. If you see '...
                    'the cannon you should place your shield '...
                    'at the aim. The cannon is still aiming '...
                    'and shooting exactly as before. You will '...
                    'collect points for catching '...
                    'balls exactly as before. But now, if you '...
                    'cannot see the cannon, you must place your '...
                    'shield at the position where you think '...
                    'the cannon is aimed.\n\n'...
                    'Since you will see each ball shot from '...
                    'the cannon, you will be able to use '...
                    'the locations of past shots to inform '...
                    'your decision.'];
                
                
            else
                txt = ['In this block everything will exactly '...
                    'be the same except that you will no '...
                    'longer see the cannon. The cannon is '...
                    'still aiming and shooting exactly as '...
                    'before. You will be paid for catching '...
                    'balls exactly as before. But now you '...
                    'must place your shield at the position '...
                    'where you think the cannon is aimed.\n\n'...
                    'Since you will see each ball shot from '...
                    'the cannon, you will be able to use '...
                    'the locations of past shots to inform '...
                    'your decision.'];
            end
            
            feedback = false;
            fw = al_bigScreen(taskParam, taskParam.strings.txtPressEnter, header, txt, feedback);
            if fw == 1
                screenIndex = screenIndex + 1;
                
            elseif bw == 1
                screenIndex = screenIndex - 3;
            end
            
            WaitSecs(0.1);
            
        case 4
            break
    end
end

end