function MainAndFollowCannon_CannonVisibleNoNoise
%MAINANDFOLLOWCANNON_CANNONVISIBLENONOISE   This function runs the practice session for the change point and follow-cannon conditions
%
%   Input
%       ~
%
%   Output
%       ~


screenIndex = 1;

while 1
    
    switch(screenIndex)
        
        case 1
            
            if isequal(taskParam.gParam.taskType, 'dresden')
                header = 'Erste Übung';
            else
                header = 'First Practice';
            end
            
            if isequal(whichPractice, 'mainPractice') || isequal(whichPractice, 'followCannonPractice')
                
                if isequal(taskParam.gParam.taskType, 'dresden')
                    
                    if isequal(subject.group, '1')
                        
                        
                        txt=['In dieser Übung ist das Ziel '...
                            'möglichst viele Kanonenkugeln '...
                            'abzuwehren. Die Kanone bleibt '...
                            'meistens an der selben Stelle. '...
                            'Manchmal dreht sich die Kanone '...
                            'allerdings und zielt auf eine '...
                            'andere Stelle. Wenn du den '...
                            'orangenen Punkt genau auf die '...
                            'Stelle steuerst, auf die die '...
                            'Kanone zielt, wehrst du die '...
                            'meisten Kugeln ab.\n\nWenn du '...
                            'deinen Punkt zu oft neben die '...
                            'anvisierte Stelle steuerst, wird '...
                            'die Übung wiederholt.'];
                        
                    else
                        txt=['In dieser Übung ist das Ziel '...
                            'möglichst viele Kanonenkugeln '...
                            'abzuwehren. Die Kanone bleibt '...
                            'meistens an der selben Stelle. '...
                            'Manchmal dreht sich die Kanone '...
                            'allerdings und zielt auf eine '...
                            'andere Stelle. Wenn Sie den '...
                            'orangenen Punkt genau auf die '...
                            'Stelle steuern, auf die die '...
                            'Kanone zielt, wehren Sie die '...
                            'meisten Kugeln ab.\n\nWenn Sie '...
                            'Ihren Punkt zu oft neben die '...
                            'anvisierte Stelle steuern, '...
                            'wird die Übung wiederholt.'];
                        
                        
                        %end
                    end
                elseif isequal(taskParam.gParam.taskType, 'ARC')
                    
                    txt = ['You will will now need to catch '...
                        'cannonballs shot from a cannon.'...
                        'The cannon will usually remain aimed '...
                        'at the same location. However, '...
                        'occasionally the cannon will be '...
                        'reaimed to a completely different '...'
                        'part of the circle.\n\nTo earn most '...
                        'points you should center your shield '...
                        'on the location at which the cannon '...
                        'is aimed.'];
                    
                else
                    txt = ['You will will now need to catch '...
                        'cannonballs shot from a cannon.'...
                        'The cannon will usually remain aimed '...
                        'at the same location. However, '...
                        'occasionally the cannon will be '...
                        'reaimed to a completely different '...'
                        'part of the circle.\n\nTo earn most '...
                        'money you should center your shield '...
                        'on the location at which the cannon '...
                        'is aimed.'];
                    
                end
                
            else
                
                if isequal(subject.group, '1')
                    txt=['In dieser Übung ist das Ziel '...
                        'möglichst viele Kanonenkugeln '...
                        'aufzusammeln. Du wirst feststellen, '...
                        'dass die Kanone relativ ungenau '...
                        'schießt, aber meistens auf die selbe '...
                        'Stelle zielt. Manchmal dreht sich die '...
                        'Kanone allerdings auch und zielt auf '...
                        'eine andere Stelle. Du verdienst am '...
                        'meisten, wenn du den orangenen Punkt '...
                        'genau auf den schwarzen Strich '...
                        'steuerst, weil du so sicher die Kugel '...
                        'aufsammelst. \n\nWenn du die Kugel zu '...
                        'oft nicht aufsammelst, wird die '...
                        'Übung wiederholt.'];
                else
                    txt=['In dieser Übung ist das Ziel '...
                        'möglichst viele Kanonenkugeln '...
                        'aufzusammeln. Sie werden feststellen, '...
                        'dass die Kanone relativ ungenau '...
                        'schießt, aber meistens auf die selbe '...
                        'Stelle zielt. Manchmal dreht sich die '...
                        'Kanone allerdings auch und zielt auf '...
                        'eine andere Stelle. Sie verdienen am '...
                        'meisten, wenn Sie den orangenen Punkt '...
                        'genau auf den schwarzen Strich '...
                        'steuern, weil Sie so sicher die Kugel '...
                        'aufsammeln. \n\nWenn Sie die Kugel zu '...
                        'oft nicht aufsammeln, wird die '...
                        'Übung wiederholt.'];
                end
                
            end
            feedback = false;
            fw = al_bigScreen(taskParam, taskParam.strings.txtPressEnter, header, txt, feedback);
            
            if fw == 1
                screenIndex = screenIndex + 1;
            end
            WaitSecs(0.1);
            
        case 2
            
            condition = 'mainPractice_1';
            LoadData = 'CP_NoNoise';
            %                function MainAndFollowCannon_CannonVisibleNoNoise
            
            screenIndex = 1;
            
            while 1
                
                switch(screenIndex)
                    
                    case 1
                        
                        if isequal(taskParam.gParam.taskType, 'dresden')
                            header = 'Erste Übung';
                        else
                            header = 'First Practice';
                        end
                        
                        if isequal(whichPractice, 'mainPractice')...
                                || isequal(whichPractice,...
                                'followCannonPractice')
                            
                            if isequal(taskParam.gParam.taskType, 'dresden')
                                
                                if isequal(subject.group, '1')
                                    
                                    
                                    txt=['In dieser Übung ist das Ziel '...
                                        'möglichst viele Kanonenkugeln '...
                                        'abzuwehren. Die Kanone bleibt '...
                                        'meistens an der selben Stelle. '...
                                        'Manchmal dreht sich die Kanone '...
                                        'allerdings und zielt auf eine '...
                                        'andere Stelle. Wenn du den '...
                                        'orangenen Punkt genau auf die '...
                                        'Stelle steuerst, auf die die '...
                                        'Kanone zielt, wehrst du die '...
                                        'meisten Kugeln ab.\n\nWenn du '...
                                        'deinen Punkt zu oft neben die '...
                                        'anvisierte Stelle steuerst, wird '...
                                        'die Übung wiederholt.'];
                                    
                                else
                                    txt=['In dieser Übung ist das Ziel '...
                                        'möglichst viele Kanonenkugeln '...
                                        'abzuwehren. Die Kanone bleibt '...
                                        'meistens an der selben Stelle. '...
                                        'Manchmal dreht sich die Kanone '...
                                        'allerdings und zielt auf eine '...
                                        'andere Stelle. Wenn Sie den '...
                                        'orangenen Punkt genau auf die '...
                                        'Stelle steuern, auf die die '...
                                        'Kanone zielt, wehren Sie die '...
                                        'meisten Kugeln ab.\n\nWenn Sie '...
                                        'Ihren Punkt zu oft neben die '...
                                        'anvisierte Stelle steuern, '...
                                        'wird die Übung wiederholt.'];
                                    
                                    
                                    %end
                                end
                            elseif isequal(taskParam.gParam.taskType, 'ARC')
                                
                                txt = ['You will will now need to catch '...
                                    'cannonballs shot from a cannon.'...
                                    'The cannon will usually remain aimed '...
                                    'at the same location. However, '...
                                    'occasionally the cannon will be '...
                                    'reaimed to a completely different '...'
                                    'part of the circle.\n\nTo earn most '...
                                    'points you should center your shield '...
                                    'on the location at which the cannon '...
                                    'is aimed.'];
                                
                            else
                                txt = ['You will will now need to catch '...
                                    'cannonballs shot from a cannon.'...
                                    'The cannon will usually remain aimed '...
                                    'at the same location. However, '...
                                    'occasionally the cannon will be '...
                                    'reaimed to a completely different '...'
                                    'part of the circle.\n\nTo earn most '...
                                    'money you should center your shield '...
                                    'on the location at which the cannon '...
                                    'is aimed.'];
                                
                            end
                            
                        else
                            
                            if isequal(subject.group, '1')
                                txt=['In dieser Übung ist das Ziel '...
                                    'möglichst viele Kanonenkugeln '...
                                    'aufzusammeln. Du wirst feststellen, '...
                                    'dass die Kanone relativ ungenau '...
                                    'schießt, aber meistens auf die selbe '...
                                    'Stelle zielt. Manchmal dreht sich die '...
                                    'Kanone allerdings auch und zielt auf '...
                                    'eine andere Stelle. Du verdienst am '...
                                    'meisten, wenn du den orangenen Punkt '...
                                    'genau auf den schwarzen Strich '...
                                    'steuerst, weil du so sicher die Kugel '...
                                    'aufsammelst. \n\nWenn du die Kugel zu '...
                                    'oft nicht aufsammelst, wird die '...
                                    'Übung wiederholt.'];
                            else
                                txt=['In dieser Übung ist das Ziel '...
                                    'möglichst viele Kanonenkugeln '...
                                    'aufzusammeln. Sie werden feststellen, '...
                                    'dass die Kanone relativ ungenau '...
                                    'schießt, aber meistens auf die selbe '...
                                    'Stelle zielt. Manchmal dreht sich die '...
                                    'Kanone allerdings auch und zielt auf '...
                                    'eine andere Stelle. Sie verdienen am '...
                                    'meisten, wenn Sie den orangenen Punkt '...
                                    'genau auf den schwarzen Strich '...
                                    'steuern, weil Sie so sicher die Kugel '...
                                    'aufsammeln. \n\nWenn Sie die Kugel zu '...
                                    'oft nicht aufsammeln, wird die '...
                                    'Übung wiederholt.'];
                            end
                            
                        end
                        feedback = false;
                        fw = al_bigScreen(taskParam, taskParam.strings.txtPressEnter, header, txt, feedback);
                        
                        if fw == 1
                            screenIndex = screenIndex + 1;
                        end
                        WaitSecs(0.1);
                        
                    case 2
                        
                        condition = 'mainPractice_1';
                        LoadData = 'CP_NoNoise';
                        %                     [taskParam, practData] = practLoop(taskParam,...
                        %                         subject, taskParam.gParam.haz(1),...
                        %                         taskParam.gParam.concentration(3),...
                        %                         cannon, condition, LoadData);
                        keyboard
                        header = 'new practice'
                        txt = 'new practice'
                        feedback = false;
                        fw = al_bigScreen(taskParam, taskParam.strings.txtPressEnter, header, txt, feedback);
                        % if fw == 1
                        %    screenIndex = screenIndex + 1;
                        %elseif bw == 1
                        %    screenIndex = screenIndex - 3;
                        % end
                        
                        % added this (02.01.17) to get rid of practLoop
                        [taskData, Data] =  al_mainLoop(taskParam, taskParam.gParam.haz(1), taskParam.gParam.concentration(3), condition, subject);
                        
                        %                     [txt, header] = al_feedback(taskData, taskParam,...
                        %                         subject, condition);
                        %                     feedback = true;
                        %                     warning('vorher')
                        %                     al_bigScreen(taskParam,...
                        %                         taskParam.strings.txtPressEnter,...
                        %                         header, txt, feedback);
                        %                     warning('nachher')
                        screenIndex = screenIndex + 1;
                        
                        WaitSecs(0.1);
                        
                    case 3
                        
                        screenIndex = performanceCriterion(screenIndex, taskData);
                        
                    case 4
                        
                        break
                        
                end
                
            end
            
    end
    %[taskParam, practData] = practLoop(taskParam,...
    %                         subject, taskParam.gParam.haz(1),...
    %                         taskParam.gParam.concentration(3),...
    %                         cannon, condition, LoadData);
    keyboard
    header = 'new practice';
    txt = 'new practice';
    feedback = false;
    fw = al_bigScreen(taskParam, taskParam.strings.txtPressEnter,  header, txt, feedback);
    % if fw == 1
    %    screenIndex = screenIndex + 1;
    %elseif bw == 1
    %    screenIndex = screenIndex - 3;
    % end
    
    % added this (02.01.17) to get rid of practLoop
    [taskData, Data] =  al_mainLoop(taskParam, taskParam.gParam.haz(1), taskParam.gParam.concentration(3), condition, subject);
    
    %                     [txt, header] = al_feedback(taskData, taskParam,...
    %                         subject, condition);
    %                     feedback = true;
    %                     warning('vorher')
    %                     al_bigScreen(taskParam,...
    %                         taskParam.strings.txtPressEnter,...
    %                         header, txt, feedback);
    %                     warning('nachher')
    screenIndex = screenIndex + 1;
    
    WaitSecs(0.1);
    
    case 3
        
        screenIndex = performanceCriterion...
            (screenIndex, taskData);
        
        case 4
            
            break
            
end

end

end