function MainAndFollowCannon_CannonVisibleNoise(whichPractice, taskParam, subject)

    screenIndex = 1;

    while 1

        switch(screenIndex)

            case 1

                %if isequal(taskParam.gParam.taskType, 'ARC')
                 %   warning('hier nur für ARC spezifiziert! noch für reversal und so anpassen')
                if isequal(whichPractice, 'mainPractice')...
                        || isequal(whichPractice,...
                        'followCannonPractice')
                    if isequal(taskParam.gParam.taskType, 'dresden')
                        header = 'Zweite Übung';
                    else
                        header = 'First Practice';
                    end

                    if isequal(taskParam.gParam.taskType, 'dresden')

                        if isequal(subject.group, '1')

                            txt=['Weil die Kanone schon sehr alt '...
                                'ist, sind die Schüsse ziemlich '...
                                'ungenau. Das heißt, auch wenn '...
                                'du genau auf das Ziel gehst, '...
                                'kannst du die Kugel verfehlen. '...
                                'Die Ungenauigkeit ist zufällig, '...
                                'dennoch wehrst du die meisten '...
                                'Kugeln ab, wenn du den orangenen '...
                                'Punkt genau auf die Stelle '...
                                'steuerst, auf die die Kanone '...
                                'zielt.\n\nIn der nächsten Übung '...
                                'sollst du mit der Ungenauigkeit '...
                                'der Kanone erstmal vertraut '...
                                'werden. Lasse den orangenen Punkt '...
                                'bitte immer auf der anvisierten '...
                                'Stelle stehen. Wenn du deinen '...
                                'Punkt zu oft '...
                                'neben die anvisierte Stelle '...
                                'steuerst, wird die Übung '...
                                'wiederholt.'];

                        else

                            txt=['Weil die Kanone schon sehr alt '...
                                'ist, sind die Schüsse ziemlich '...
                                'ungenau. Das heißt, auch wenn '...
                                'Sie genau auf das Ziel gehen, '...
                                'können Sie die Kugel verfehlen. '...
                                'Die Ungenauigkeit ist zufällig, '...
                                'dennoch wehren Sie die meisten '...
                                'Kugeln ab, wenn Sie den orangenen '...
                                'Punkt genau auf die Stelle '...
                                'steuern, auf die die Kanone '...
                                'zielt.\n\nIn der nächsten Übung '...
                                'sollen Sie mit der Ungenauigkeit '...
                                'der Kanone erstmal vertraut werden. '...
                                'Lassen Sie den orangenen Punkt '...
                                'bitte immer auf der anvisierten '...
                                'Stelle stehen. Wenn Sie Ihren '...
                                'Punkt zu oft neben die anvisierte '...
                                'Stelle steuern, wird die '...
                                'Übung wiederholt.'];

                        end
                    else
                         txt = ['You will will now need to catch '...
                            'cannonballs shot from a cannon that '....
                            'is not perfectly accurate. '...
                            'The cannon will usually remain aimed '...
                            'at the same location. However, '...
                            'occasionally the cannon will be '...
                            'reaimed to a completely different '...'
                            'part of the circle.\n\nTo earn most '...
                            'points you should center your shield '...
                            'on the location at which the cannon '...
                            'is aimed.'];
%                             txt = ['In this block you will encounter a '...
%                                 'cannon that is not perfectly '...
%                                 'accurate. On some trials it will '...
%                                 'shoot a bit above where it is aimed '...
%                                 'and on other trials a bit below. '...
%                                 'Your best strategy is still to place '...
%                                 'the shield in the location where the '...
%                                 'cannon is aimed.\n\nThe cannon will '...
%                                 'still remain stable on most trials '...
%                                 'but be reaimed to another location '...
%                                 'on the cirlce occasionally.'];
                    end

                else

                    header = 'Erste Übung';


                    if isequal(subject.group, '1')




                        txt=['In dieser Übung ist das Ziel möglichst '...
                            'viele Kanonenkugeln aufzusammeln. '...
                            'Du wirst feststellen, dass die Kanone '...
                            'relativ ungenau schießt, aber meistens '...
                            'auf die selbe Stelle zielt. Diese '...
                            'Ungenauigkeit ist zufällig. Manchmal '...
                            'dreht sich die Kanone '...
                            'auch und zielt auf eine andere Stelle. '...
                            'Du verdienst am meisten, wenn du den '...
                            'orangenen Punkt genau auf den '...
                            'schwarzen Strich steuerst, weil du '...
                            'so sicher die Kugel aufsammelst. '...
                            '\n\nWenn du die Kugel zu oft nicht '...
                            'aufsammelst, wird die Übung wiederholt.'];
                    else

                        txt=['In dieser Übung ist das Ziel möglichst '...
                            'viele Kanonenkugeln aufzusammeln. '...
                            'Du wirst feststellen, dass die Kanone '...
                            'relativ ungenau schießt, aber meistens '...
                            'auf die selbe Stelle zielt. Diese '...
                            'Ungenauigkeit ist zufällig. Manchmal '...
                            'dreht sich die Kanone '...
                            'auch und zielt auf eine andere Stelle. '...
                            'Du verdienst am meisten, wenn du den '...
                            'orangenen Punkt genau auf den '...
                            'schwarzen Strich steuerst, weil du '...
                            'so sicher die Kugel aufsammelst. '...
                            '\n\nWenn du die Kugel zu oft nicht '...
                            'aufsammelst, wird die Übung wiederholt.'];
                    end


                    %end

                end

                feedback = false;
                fw = al_bigScreen(taskParam,...
                    taskParam.strings.txtPressEnter,...
                    header, txt, feedback);
                if fw == 1
                    screenIndex = screenIndex + 1;
                %elseif bw == 1
                %    screenIndex = screenIndex - 3;
                end


                WaitSecs(0.1);
            case 2


                LoadData = 'CP_Noise';
                if isequal(whichPractice, 'mainPractice')
                    condition = 'mainPractice_2';
                elseif isequal(whichPractice, 'followCannonPractice')
                    condition = 'followCannonPractice';
                elseif isequal(whichPractice, 'followOutcomePractice')
                    condition = 'followOutcomePractice';
                end


%                     [taskParam, practData] = practLoop(taskParam,...
%                         subject, taskParam.gParam.haz(1),...
%                         taskParam.gParam.concentration(1),...
%                         cannon, condition,LoadData);
                % added this (02.01.17) to get rid of practLoop
                [taskData, Data] =  al_mainLoop(taskParam,...
                    taskParam.gParam.haz(1),...
                    taskParam.gParam.concentration(3),...
                        condition, subject);


%                     [txt, header] = al_feedback(taskData,...
%                         taskParam, subject, condition);
%                     
%                     feedback = true;
%                     fw = al_bigScreen(taskParam,...
%                         taskParam.strings.txtPressEnter,...
%                         header, txt, feedback);
%                     
%                     if fw == 1
                    screenIndex = screenIndex + 1;
               % elseif bw == 1
                    %screenIndex = screenIndex - 1;
                %end
                WaitSecs(0.1);

            case 3

                screenIndex = performanceCriterion(screenIndex, taskData, whichPractice, taskParam);

            case 4

                if isequal(whichPractice, 'followCannonPractice')
                    FollowCannonJustInstructions

                elseif isequal(whichPractice, 'followOutcomePractice')
                    break
                else
                    MainJustInstructions(taskParam)
                end

                break
        end

    end

end