function [screenIndex] = performanceCriterion(screenIndex, taskData, whichPractice, taskParam)
%PERFORMANCECRITERION   This function checks if participants have reached
%   a pre-specified performance criterion to continue with the intructions
%
%   Input
%       screenIndex: indicates current screen of instruction phase
%       taskData: data of practice session
%       whichPractice: indicates which practice condition will be run
%       taskParam: structure containing task parameters
%
%   Output
%       screenIndex: updated screenIndex


if isequal(whichPractice, 'mainPractice') || isequal(whichPractice, 'followCannonPractice') || isequal(whichPractice, 'chinese')
    sumCannonDev = sum(taskData.memErr >= taskParam.gParam.practiceTrialCriterion);
elseif isequal(whichPractice, 'followOutcomePractice')
    sumCannonDev = sum(practData.controlDev >= taskParam.gParam.practiceTrialCriterion);
end

if sumCannonDev >= 4
    if isequal(taskParam.gParam.taskType, 'dresden')
        
        if isequal(whichPractice, 'mainPractice') || isequal(whichPractice, 'followCannonPractice')
            header = 'Wiederholung der Übung';
            if isequal(subject.group, '1')
                txt = ['In der letzten Übung hast du dich zu '...
                    'häufig vom Ziel der Kanone wegbewegt. '...
                    'Du kannst mehr Kugeln abwehren, wenn du '...
                    'immer auf dem Ziel der Kanone bleibst!'...
                    '\n\nIn der nächsten Runde kannst nochmal '...
                    'üben. Wenn du noch Fragen hast, kannst du '...
                    'dich auch an den Versuchsleiter wenden.'];
            else
                txt = ['In der letzten Übung haben Sie sich zu '...
                    'häufig vom Ziel der Kanone wegbewegt. '...
                    'Sie können mehr Kugeln abwehren, wenn Sie '...
                    'immer auf dem Ziel der Kanone bleiben!'...
                    '\n\nIn der nächsten Runde können Sie '...
                    'nochmal üben. Wenn Sie noch Fragen haben, '...
                    'können Sie sich auch an den '...
                    'Versuchsleiter wenden.'];
            end
        elseif isequal(whichPractice, 'followOutcomePractice')
            header = 'Wiederholung der Übung';
            if isequal(subject.group, '1')
                txt = ['In der letzten Übung hast du die '...
                    'jeweils letzte Kugel zu selten '...
                    'aufgesammelt.\n\nIn der nächsten Runde '...
                    'kannst nochmal üben. Wenn du noch Fragen '...
                    'hast, kannst du dich auch an den '...
                    'Versuchsleiter wenden.'];
            else
                txt = ['In der letzten Übung haben Sie die '...
                    'jeweils letzte Kugel zu selten '...
                    'aufgesammelt.\n\nIn der nächsten Runde '...
                    'können Sie nochmal üben. Wenn Sie noch '...
                    'Fragen haben, können Sie sich auch an '...
                    'den Versuchsleiter wenden.'];
            end
        end
        
    elseif isequal(taskParam.gParam.taskType, 'oddball') || isequal(taskParam.gParam.taskType, 'ARC')
        header = 'Try it again!';
        txt = ['In that block your shield was not always '...
            'placed where the cannon was aiming. Remember: '...
            'Placing your shield where the cannon is aimed '...
            'will be the best way to catch cannonballs. Now try again.'];
    elseif isequal(taskParam.gParam.taskType, 'chinese')
        header = 'Wiederholung der Übung!';
        txt = ['In der letzten Übung hast du dich zu '...
            'häufig vom Ziel des Gegners wegbewegt. '...
            'Du kannst mehr Kanonenkugeln abwehren, wenn du '...
            'immer auf dem Ziel des Gegners bleibst!'...
            '\n\nIn der nächsten Runde kannst nochmal '...
            'üben. Wenn du noch Fragen hast, kannst du '...
            'dich auch an den Versuchsleiter wenden.'];
    end
    feedback = false;
    fw = al_bigScreen(taskParam,...
        taskParam.strings.txtPressEnter, header, txt, feedback);
    if fw == 1
        screenIndex = screenIndex - 1;
    elseif bw == 1
        screenIndex = screenIndex - 2;
    end
else
    screenIndex = screenIndex + 1;
end

WaitSecs(0.1);
end